# Generated by Django 4.0.5 on 2022-06-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioKniga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('photo', models.ImageField(null=True, upload_to='book')),
                ('author', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('audio_url', models.URLField(blank=True, max_length=1000)),
            ],
        ),
    ]
