# Generated by Django 4.0.5 on 2022-06-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiokniga',
            name='audio_url2',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='audiokniga',
            name='audio_url3',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='audiokniga',
            name='audio_url4',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='audiokniga',
            name='audio_url5',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='audiokniga',
            name='audio_url6',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
