# Generated by Django 4.0.5 on 2022-06-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_audiokniga_audio_url2_audiokniga_audio_url3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiokniga',
            name='audio_url2',
        ),
        migrations.RemoveField(
            model_name='audiokniga',
            name='audio_url3',
        ),
        migrations.RemoveField(
            model_name='audiokniga',
            name='audio_url4',
        ),
        migrations.RemoveField(
            model_name='audiokniga',
            name='audio_url5',
        ),
        migrations.RemoveField(
            model_name='audiokniga',
            name='audio_url6',
        ),
    ]
